export const ADD_MESSAGE = 'ADD_MESSAGE';
export const ADD_MESSAGE_SUCCESS = 'ADD_MESSAGE_SUCCESS';
export const ADD_MESSAGE_FAILURE = 'ADD_MESSAGE_FAILURE';

export const EDIT_MESSAGE = 'EDIT_MESSAGE';
export const EDIT_MESSAGE_SUCCESS = 'EDIT_MESSAGE_SUCCESS';
export const EDIT_MESSAGE_FAILURE = 'EDIT_MESSAGE_FAILURE';

export const DEL_MESSAGE = 'DEL_MESSAGE';
export const DEL_MESSAGE_SUCCESS = 'DEL_MESSAGE_SUCCESS';
export const DEL_MESSAGE_FAILURE = 'DEL_MESSAGE_FAILURE';

export const ADD_THREAD = 'ADD_THREAD';
export const ADD_THREAD_SUCCESS = 'ADD_THREAD_SUCCESS';
export const ADD_THREAD_FAILURE = 'ADD_THREAD_FAILURE';

export const EDIT_THREAD = 'EDIT_THREAD';
export const EDIT_THREAD_SUCCESS = 'EDIT_THREAD_SUCCESS';
export const EDIT_THREAD_FAILURE = 'EDIT_THREAD_FAILURE';

export const DEL_THREAD = 'DEL_THREAD';
export const DEL_THREAD_SUCCESS = 'DEL_THREAD_SUCCESS';
export const DEL_THREAD_FAILURE = 'DEL_THREAD_FAILURE';

export const ADD_CHANNEL = 'ADD_CHANNEL';
export const EDIT_CHANNEL = 'EDIT_CHANNEL';
export const DEL_CHANNEL = 'DEL_CHANNEL';

export const CHANNELS = 'REC_CHANNELS';
export const CHANNELS_SUCCESS = 'CHANNELS_SUCCESS';
export const CHANNELS_FAILURE = 'CHANNELS_FAILURE';

export const CHANNEL = 'CHANNEL';
export const CHANNEL_SUCCESS = 'CHANNEL_SUCCESS';
export const CHANNEL_FAILURE = 'CHANNEL_FAILURE';

export const THREADS = 'THREADS';
export const THREADS_SUCCESS = 'THREADS_SUCCESS';
export const THREADS_FAILURE = 'THREADS_FAILURE';

export const THREAD = 'THREAD';
export const THREAD_SUCCESS = 'THREAD_SUCCESS';
export const THREAD_FAILURE = 'THREAD_FAILURE';

export const MESSAGES = 'MESSAGES';
export const MESSAGES_SUCCESS = 'MESSAGES_SUCCESS';
export const MESSAGES_FAILURE = 'MESSAGES_FAILURE';

export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const REGISTER = 'REGISTER';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

export const REAUTH = 'REAUTH';
export const REAUTH_SUCCESS = 'REAUTH_SUCCESS';
export const REAUTH_FAILURE = 'REAUTH_FAILURE';

export const SIGNUP = 'SIGNUP';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';
